project_id = "vrfkvcalqyzolqdshasj"

[functions.stripe-webhook]
verify_jwt = false

[functions.reschedule-booking]
verify_jwt = false

[functions.manage-venue-staff]
verify_jwt = false

[functions.ban-group-member]
verify_jwt = false

[functions.kick-challenge-player]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.transfer-payment]
verify_jwt = false
